### ISSUE TITLE
[BUG] SIRIUS 6.0.6 - Java heap space error on structure search

### ISSUE THREAD

**Issue by zglong1** [sirius-ms/sirius#213] opened 2024-10-29 13:22 UTC
**Bug description**
> When performing the structure search step, both in the GUI and CLI, the run gets to ~58% before exiting with a Java heap space error.

**Steps To Reproduce**
> Download the project, open in SIRIUS 6.0.6, and run a 'Compute All' -> 'Structure DB Search'.

**Example data** 
> Project File: https://www.dropbox.com/scl/fi/uvei1gwfrtiu86wu530tj/SIRIUS_Project_DCap_Negative_CLI_20241025_15.sirius?rlkey=ld3ryqh5eqexu0xawesyvcnmu&st=b8faay6p&dl=0
> Source mgf File: https://www.dropbox.com/scl/fi/xdygcl31yl6awfckj2pt8/SIRIUS_Export_Bug_Negative_20241004.mgf?rlkey=snhafyscp04ocavvyfzapense&dl=0

**System Info (please complete the following information):**
 - Windows 11 Pro
 - SIRIUS 6.0.6
 - AMD Ryzen 9 9950x 16-Core 4.3GHz, 192 GB DDR5 RAM

**Comment by zglong1** [comment] 2024-10-29 15:51
The structure search was done with default libraries/settings.

Earlier in the project, starting from scratch, the settings are as follows:

config --FormulaSearchSettings.applyFormulaConstraintsToBottomUp=false --IsotopeSettings.filter=true --UseHeuristic.useOnlyHeuristicAboveMz=2000 --FormulaSearchDB=, --Timeout.secondsPerTree=0 --FormulaSettings.enforced=H,C,N,O,P --Timeout.secondsPerInstance=300 --AlgorithmProfile=qtof --SpectralMatchingMassDeviation.allowedPeakDeviation=50.0ppm --AdductSettings.ignoreDetectedAdducts=false --AdductSettings.enforced=, --AdductSettings.prioritizeInputFileAdducts=true --UseHeuristic.useHeuristicAboveMz=2000 --IsotopeMs2Settings=IGNORE --MS2MassDeviation.allowedMassDeviation=50.0ppm --SpectralMatchingMassDeviation.allowedPrecursorDeviation=50.0ppm --FormulaSearchSettings.performDeNovoBelowMz=Infinity --FormulaSearchSettings.applyFormulaConstraintsToDatabaseCandidates=false --EnforceElGordoFormula=false --NumberOfCandidatesPerIonization=10 --FormulaSettings.detectable=S --NumberOfCandidates=250 --AdductSettings.fallback=[[M-H]-,[M+Cl]-,[M-H2O-H]-,[M-CO2-H]-,[M+H2O-H]-] --FormulaSearchSettings.performBottomUpAboveMz=Infinity --RecomputeResults=false spectra-search formulas

After this, I did a bottom-up search with the same restrictions/settings. This was followed by another Denovo search with heuristic mass thresholds both set to 0. This was also followed by a matching bottom-up search, and finally a database search.

After SIRIUS, ZODIAC was run using default settings, except for candidates@300mz = 50

CSIFingerID was run using default settings, same for structure DB search.

**Comment by MartinHoffmannJena** [comment] 2024-10-30 18:51
I'm assuming this is happening because you are running SIRIUS with an allowed MS2 mass deviation of 50 ppm (--MS2MassDeviation.allowedMassDeviation=50.0ppm).

This is an unreasonable setting for high res MS/MS data and will inflate the space of possible formulas by a very large amount. You are also choosing to store 250 candidates instead of the usual 10.

I'm closing this issue for now since it is likely not a bug. If you are experiencing this with more reasonable parameters as well, feel free to reopen it

**Closed by MartinHoffmannJena** 2024-10-30 18:51 UTC
Labels: probable bug

**Comment by Elbeo137** [comment] 2025-02-15 12:24
Good afternoon,

I would also ask you about Terminating due to java.lang.OutOfMemoryError: Java heap space

I have 4Ghz 6 core i5 and 64GB RAM  however I increased a virtual memory to have 251 GB committed. 

I also changed parameters in app/ .cfg firstly to java-options=-XX:MaxRAMPercentage=100 and then to java-options=-Xmx250G (counting a virtual memory) 

I found the term "heap" in profiles default and profile.jfc but they don´t differ in "heap" lines. 

I don´t know what exactly "heap space" means but my question is could I change any parameter to overcome this error? 

The version 4 was able to compute all ions (at least to give a result if it is possible or not) however version 6.1.1 is terminating in one (big 1289,248 m/z with RT 10,32 min) ion. 

I see differences in TOPs between version v4 and v6 and v6 was also able to compute more ions (except this single ion causing heap space error) 

I´m working with default parameters for SIRIUS formula identification and I have an academic licence. 

Thank you very much for your answer. 

![Image](https://github.com/user-attachments/assets/af8d2fba-fbe9-472a-b964-991a21f1404e)
