### ISSUE TITLE
DDA data from Synapt - no MS after import of the mzML file, centroid 

### ISSUE THREAD

**Issue by ana-kovacic** [sirius-ms/sirius#178] opened 2024-07-31 15:07 UTC
Hi,

a few days ago, after importing DDA centroid data, acquired on SynaptXS, waters, mzML I was able to see MS1 as well as MS2 in sirius, while today after import of the same file I am able to obtain only MS1 in sirius. I have tried also with different computers, but still, only MS1 is observed. 
Do you know what could be the reason? 
Please find one file example at this link: https://drive.google.com/file/d/1kBrQBFq6m1zDCc5dId5bNcQ4uqguQpDM/view?usp=sharing

Thank you.
Best, Ana

**Comment by ana-kovacic** [comment] 2024-07-31 16:52
Hi, I notice what is the difference and most probably the issue, namely it is working with 6.0.0 version while not importing MS2 with the newest version, 6.0.1
Please let me know if you think there is a possibilty to import the MS2 also with the newset version. 
Best
Ana

**Comment by zglong1** [comment] 2024-07-31 16:55
I'm also having issues with this. SIRIUS 6.0.1, Windows 10. mzML files I've previously uploaded to earlier SIRIUS versions no longer import correctly, I end up with 0 of 0 (15386) features for a single mzML file, and when trying to align multiple mzML files on loading them in it gives an error about 'charge can't be 0'. Other sets of mzML files don't have the charge issue, but they all fail to meaningfully import. I get tens of thousands of 'features' (normally less than a thousand), none of which are selectable despite disabling and feature quality restrictions.

**Comment by MartinHoffmannJena** [comment] 2024-08-29 12:42
Hi, 

That example file you provided works as intended for me on SIRIUS 6.0.4. If you have any other files that dont work as they should, please attach them here if possible

**Comment by mfleisch** [comment] 2024-09-02 20:25
Since the provided data is working with the latest updates, I close this issue. Please open a new one if there are still problems with the import of your data.

**Closed by mfleisch** 2024-09-02 20:25 UTC
